# Generated by Django 3.2.7 on 2021-09-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('accountNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('balance', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('txnId', models.CharField(max_length=10)),
                ('amount', models.FloatField(max_length=10)),
                ('narration', models.CharField(max_length=200)),
                ('valueDate', models.DateField()),
                ('balance', models.FloatField(max_length=10)),
                ('accountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
