# Generated by Django 3.2.7 on 2021-09-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='valueDate',
            field=models.CharField(max_length=20),
        ),
    ]
