# Generated by Django 3.2.7 on 2021-10-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='accountNumber',
            field=models.CharField(max_length=20),
        ),
    ]
